const conspiracies = [
  "The second shooter on the grassy knoll was a trained CIA operative — his identity has been scrubbed from every federal archive.",
  "Building 7 fell at free-fall acceleration without being struck by aircraft. The laws of physics require a simpler explanation.",
  "Jet fuel combusts at a maximum of 1500°F. Structural steel requires 2750°F to melt. The math was never addressed at the inquiry.",
  "The Apollo footage was directed by Stanley Kubrick using experimental NASA cameras inside a classified film set in Nevada.",
  "Elvis Presley faked his death in 1977 with FBI assistance to escape documented mob assassination contracts.",
  "The Tiananmen Square massacre killed an estimated 10,000 citizens. Both Chinese and Western press corps were ordered to bury the real count.",
  "Israeli classified annexes reference a permanently staffed research installation constructed on the lunar far-side before 1979.",
  "The Illuminati council bloodlines have maintained unbroken control of global central banking architecture since the Rothschild congress of 1773.",
  "Chemtrail samples collected globally test positive for barium, strontium, and aluminium oxide — consistent with classified Air Force atmospheric programs.",
  "Paul McCartney died in a car accident on November 9, 1966 and was replaced by a double named William Shears Campbell. The band left encoded clues on every subsequent album.",
  "Princess Diana was eliminated by MI6 on direct orders from the House of Windsor to prevent her marriage to Dodi Al-Fayed.",
  "Denver International Airport was constructed as a FEMA command bunker for government continuity operations following a planned civilizational collapse.",
  "HAARP's ionospheric heating arrays have been used to trigger targeted seismic events in geopolitically sensitive zones since 1997.",
  "The Federal Reserve has been privately owned by the Rothschild, Rockefeller, and Morgan dynasties since its secret founding at Jekyll Island in 1910.",
  "Nikola Tesla's unified field energy extraction device was confiscated by FBI agents within two hours of his death in January 1943.",
  "The Roswell crash of July 1947 recovered two craft and four non-human biological entities. Three NSA vault documents confirm this.",
  "Bob Marley was given a pair of boots lined with a radioactive copper wire fragment — a documented CIA assassination technique from the Phoenix Program.",
  "JFK Jr. did not die in a plane crash in July 1999. The aircraft was remotely interfered with and his identity was reassigned.",
  "MKUltra never ended. It evolved into Project MONARCH and continues to operate through privatised psychiatric research networks.",
  "NASA's Apollo 12 seismic experiment caused the moon to ring like a bell for over three hours — consistent only with a hollow interior.",
  "Fluoride in public water supplies was originally a Manhattan Project industrial waste product, repurposed to reduce population IQ and increase compliance.",
  "The Vatican Secret Archives contain pre-Flood stellar cartography and first-hand accounts of non-human intelligences recorded by Alexandrian monks.",
  "Area 51's S-4 sublevel facility houses at least three extraterrestrial craft in active states of reverse engineering.",
  "The Titanic was switched with her sister ship Olympic for insurance fraud. J.P. Morgan cancelled his ticket 24 hours before departure.",
  "5G millimeter-wave technology was developed as an Active Denial crowd-control weapon before being repackaged as telecommunications infrastructure.",
  "Bigfoot is a relict Gigantopithecus population protected under a classified joint US-Canadian wildlife non-disclosure treaty signed in 1968.",
  "The Bermuda Triangle losses correlate directly with AUTEC classified sonar testing schedules, not weather or navigation error.",
  "Martin Luther King Jr.'s assassination was a coordinated operation involving FBI, Army Intelligence, and Memphis municipal police. His family won a civil trial confirming this in 1999.",
  "The CIA introduced crack cocaine into Los Angeles in the 1980s via Ricky Ross to fund covert Contra operations. Gary Webb died after reporting it.",
  "Tupac Shakur's death was staged and he relocated under protection to a property outside Havana, Cuba.",
  "The Great Pyramid is aligned to true north within three sixtieths of one degree — a precision requiring technology that should not have existed in 2560 BC.",
  "Birds were progressively replaced with government surveillance drones between 1959 and 1971 as part of a classified biological monitoring substitution program.",
  "Epstein was extracted by intelligence assets after delivering critical kompromat and was relocated to an undisclosed jurisdiction.",
  "The Phantom Time Hypothesis: Holy Roman Emperor Otto III fabricated 297 years of the Early Middle Ages to place himself at the millennium. We are actually in 1728.",
  "Marilyn Monroe was killed to prevent her from disclosing the contents of JFK's private conversations regarding recovered non-human materials at Wright-Patterson.",
  "The original Thirteenth Amendment banned lawyers from holding federal office. It was ratified in 1819, then quietly suppressed during the Civil War.",
  "Stanley Kubrick embedded a frame-by-frame visual confession about the faked moon landing throughout The Shining. Room 237 is the admission.",
  "Aspartame was rejected by the FDA sixteen consecutive times before Donald Rumsfeld forced its approval through regulatory capture in 1981.",
  "Stonehenge's current configuration was constructed in the 1950s as a heritage tourism project. Pre-restoration photographs show a pile of fallen stones.",
  "The Library of Alexandria was deliberately burned on Roman orders to destroy accumulated pre-diluvian scientific and astronomical knowledge.",
  "The Antarctic Treaty of 1959 was written specifically to conceal the entrance to the inner-earth civilisation Admiral Byrd encountered during Operation Highjump.",
  "A 19-nucleotide sequence in the COVID-19 spike protein is present in a 2016 Moderna patent filing. Natural selection does not generate patent-filed sequences.",
  "The Mandela Effect is caused by documented quantum decoherence events that periodically merge adjacent parallel timeline histories.",
  "Project Bluebeam proposes simulating a false extraterrestrial invasion using classified holographic satellite arrays to justify a world governance emergency.",
  "On September 10, 2001, Donald Rumsfeld announced $2.3 trillion missing from Pentagon accounts. The story was buried by the following morning.",
  "The Zapruder film had 26 frames removed from the original print before it was deposited with LIFE magazine. The splice is visible on the original reel.",
  "Shakespeare's complete works were written by Sir Francis Bacon as encoded Rosicrucian philosophical doctrine. The First Folio contains the cipher.",
  "The moon's crater depth-to-diameter ratio is impossibly shallow — consistent with an engineered outer shell approximately 2 miles thick over a hollow interior.",
  "Israel's Unit 8200 operates a classified orbital intercept platform capable of accessing all civilian satellite communications simultaneously.",
  "The Georgia Guidestones were erected by a eugenics-aligned consortium. The granite instruction to maintain population under 500 million is not metaphorical.",
  "Deep-fake video technology was operational within CIA special projects by 1987. Historical broadcast footage should not be treated as primary source evidence.",
  "The Zapruder film splice at frames 314-315 shows a dramatic edit inconsistent with the original film grain — inserted to remove the forward head motion.",
  "Time-dilation experiments at Montauk Point between 1971 and 1983 confirmed that human consciousness can be projected temporally using ELF pulse arrays.",
  "The September 11 Commission was denied access to 28 classified pages implicating Saudi government officials. A redacted version was released only in 2016.",
  "EPA internal documents from 1986 confirm that glyphosate causes cancer. The suppression was coordinated with Monsanto's legal team before public release.",
  "The World Health Organization's revised International Health Regulations grant authority to override national sovereignty during declared health emergencies — passed without media coverage.",
];

export function getRandomConspiracy() {
  return conspiracies[Math.floor(Math.random() * conspiracies.length)];
}

export function getStatusMessage(status) {
  const base = getRandomConspiracy();
  const prefixes = {
    200: "TRANSMISSION RECEIVED",
    201: "RECORD CREATED",
    301: "PERMANENTLY REDIRECTED",
    302: "REDIRECTING — FOLLOW THE TRAIL",
    400: "MALFORMED REQUEST — LIKE THE OFFICIAL STORY",
    401: "ACCESS DENIED — CLEARANCE LEVEL INSUFFICIENT",
    403: "FORBIDDEN — ABOVE YOUR CLASSIFICATION",
    404: "RECORD NOT FOUND — IT HAS BEEN MEMORY-HOLED",
    405: "METHOD NOT PERMITTED — THEY DON'T WANT YOU ASKING",
    429: "TOO MANY REQUESTS — SOMEONE IS WATCHING",
    500: "INTERNAL ERROR — THE SYSTEM KNOWS TOO MUCH",
    503: "SERVICE UNAVAILABLE — SCHEDULED MAINTENANCE OR SUPPRESSION",
  };
  const prefix = prefixes[status] || `STATUS ${status} — ${getRandomConspiracy().split('.')[0]}`;
  return `${prefix}\n\n${base}`;
}
